import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ConditionalHeader from '@/src/components/global/ConditionalHeader';
import ConditionalNavbar from '@/src/components/global/ConditionalNavbar';
import { AuthProvider } from '@/src/context/AuthContext';
import { ThemeProvider } from 'next-themes';
import { HeaderColorProvider } from '@/src/context/HeaderColorProvider';
import { getCookie } from 'cookies-next/server';
import { cookies } from 'next/headers';
import { HeaderColor, HEADERCOLOR_OPTIONS } from '@/src/types/theme';
import { TooltipProvider } from '@/components/ui/tooltip';
import GlobalSync from '@/src/components/global/GlobalSync';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sanger under liljen',
  description: 'Generated by G01',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookie = await getCookie('headerColor', { cookies });

  const headerColor = HEADERCOLOR_OPTIONS.map((o) => o.value).includes(cookie as HeaderColor)
    ? (cookie as HeaderColor)
    : undefined;

  return (
    <html lang="en" suppressHydrationWarning data-theme={headerColor}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
        <AuthProvider>
          <GlobalSync />
          <TooltipProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem enableColorScheme>
              <HeaderColorProvider initialColor={headerColor}>
                <ConditionalHeader />

                <main className="pb-[calc(80px+env(safe-area-inset-bottom))] md:pb-20 m-5">
                  {children}
                </main>

                <ConditionalNavbar />
                <Toaster position="top-center" richColors duration={3000} />
              </HeaderColorProvider>
            </ThemeProvider>
          </TooltipProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
