import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import ConditionalHeader from '@/src/components/global/ConditionalHeader';
import ConditionalNavbar from '@/src/components/global/ConditionalNavbar';

import { AuthProvider } from '@/src/context/AuthContext';
import { ThemeProvider } from 'next-themes';
import { HeaderColorProvider } from '@/src/context/HeaderColorProvider';
import { TagFilterProvider } from '@/src/context/TagFilterContext';
import { TooltipProvider } from '@/components/ui/tooltip';

import GlobalSync from '@/src/components/global/GlobalSync';
import ServiceWorkerRegister from '@/src/components/ServiceWorkerRegister';

import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sanger under liljen',
  description: 'Generated by G01',
  manifest: '/manifest.webmanifest',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#fffdfb' },
    { media: '(prefers-color-scheme: dark)', color: '#2e2e2e' },
  ],
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Sanger under liljen',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function() {
              try {
                var d = document.documentElement;

                d.classList.remove('theme-ready');
                
                // 1. Immediate dark mode
                var theme = localStorage.getItem('theme');
                
                if (theme === 'dark') {
                  d.classList.add('dark');
                } else if (theme === 'light') {
                  d.classList.remove('dark');
                } else {
                  if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    d.classList.add('dark');
                  }
                }

                // 2. Immediate header color
                 var match = document.cookie.match(/(?:^|;\\s*)headerColor=([^;]+)/);
                  if (match && match[1]) {
                    d.setAttribute('data-theme', match[1]);
                  }
                
                // 3. Mark as ready
                d.classList.add('theme-ready');
              } catch (e) {}
            })();
          `,
          }}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden h-screen flex flex-col`}
      >
        <ServiceWorkerRegister />

        <AuthProvider>
          <GlobalSync />
          <TooltipProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem enableColorScheme>
              <HeaderColorProvider>
                <ConditionalHeader />
                <TagFilterProvider>
                  <main className="flex-1 overflow-y-auto">
                    <section className="pb-[calc(80px+env(safe-area-inset-bottom))] md:pb-20 m-5 max-w-4xl mx-auto px-5">
                      {children}
                    </section>
                  </main>
                </TagFilterProvider>
                <ConditionalNavbar />
                <Toaster position="top-center" richColors duration={3000} />
              </HeaderColorProvider>
            </ThemeProvider>
          </TooltipProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
