name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -i https://1sang.no/api/health
